### ISSUE TITLE
Create endpoint

### ISSUE THREAD

**Issue by juliofihdeldev** [SHARPRISE/bloodshare#1]
[data.txt](https://github.com/SHARPRISE/bloodshare/files/1234847/data.txt)

**Comment by aesgeorges** [comment]
Nan field 'type' de class 'Centres' lan, eske wap sevi ak yon tuple? ou bien wap entrel manuellement?

 "Centres":[
    {
        'ID':'123456',
        'lieu':'Port au prince',
        'telephone':'+50948188107',
        **'type':'PTS',**
        'lat':'',
        'log':''
        'QteDispobile':'80',
    }
]

**Comment by aesgeorges** [comment]
Lot detail, nan class 'Planifier', eske li patap mieux ke 'etat' ta yon Boolean, leu sa ou te ka renome l on bagay tankou resolved, ki tap True si don an fèt, ou False si requete lan en cours toujou. **Se just yon proposition**. Li tap sanble ak sa:

"Planifier":[
    {
        'ID_planifier':'123456',
        'QtePrevu':'Some text here',
        'date':'09/08/2017'
        'resolved': False

        'ID_users':'123456',
        'compteName':'Jean FILS JULIO',
        'GS':'O+',
        'adresse':'Delmas 38',
        'qteSang':'6',
        'photo':'"https://pbs.twimg.com/profile_images/3424509849/bfa1b9121afc39d1dcdb53cfc423bf12.jpeg"'
    }
]
